<?php
  include '../views/sections/header.html';
?>
<body class="d-flex align-items-center py-4 bg-body-tertiary">
<main class="form-signin w-100 container">
  <div class="row">
    <div class="col-xxl-4 col-xl-4 col-lg-3 col-md-3 col-sm-2 col-1"></div>
    <div class="col-xxl-4  col-xl-4 col-lg-6 col-md-6 col-sm-8 col-10">
    <div class="mb-3">
      <a href="/" class="btn btn-primary">Loja</a>
    </div>
    <?php if(isset($_GET['msg']) == 1) { ?>
      <br>
      <div class="text-success bg-success-subtle text-success-emphasis p-3"><b>Seu cadastro foi criado com sucesso!!! Faça login abaixo informando o seu email e senha!</b></div>
    <?php } ?>
    
  <form action="/login/validar" method="POST" novalidate>
  <h1 class="h3 mb-3 fw-normal">Faça Login</h1>
    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" name="email" placeholder="name@example.com">
      <label for="floatingInput">e-mail</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" name="senha" placeholder="Password">
      <label for="floatingPassword">senha</label>
    </div>
    <?php if(isset($_GET['erro']) == 2) { ?>
      <div class="bg-danger-subtle text-danger-emphasis p-3 mt-3">ATENÇÃO: e-mail ou senha inválidos!!! Por favor, informe o seu login e senha corretos!</div>
    <?php } ?>
    <div class="mt-3">
      <button class="btn btn-primary w-100 py-2" type="submit">Entrar</button>
    </div>
  </form>
  <hr>
  <h3 style="font-size: 1.3em;">Ainda não possui cadastro? Clique no botão abaixo e faça o seu cadastro!</h3>
  <a href="/login/criar-login" class="btn btn-primary">Criar Cadastro</a>
    </div>
  <div class="col-xxl-4 col-xl-4 col-lg-3 col-md-3 col-sm-2 col-1"></div>
  </div>
</main>
</body>
</html>

<!-- verifica se o Administrador já foi cadastrado na Loja Virtual -->
<?php if(!$consulta) { ?>
  
  <!-- Modal de Cadastro do Administrador -->
  <div class="modal p-4 py-md-5" tabindex="-1"  id="modalCadastroAdmin" style="display: block">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header p-5 pb-4 border-bottom-0">
          <div class="text-primary fonte-modal"><b>ATENÇÃO! O Administrador precisa ser o 1º Cadastro da Loja Virtual!</b></div>
        </div>
        <div id="form-modal-caixa" class="modal-body p-5 pt-0">
          <form id="form-modal-cad-admin" novalidate>
            <div class="form-floating mb-3">
              <input type="text" class="form-control rounded-3" id="cad-nome-admin" name="nome" placeholder="">
              <label class="fonte-modal" for="floatingInput">Admin</label>
            </div>
            <div class="form-floating mb-3">
              <input type="email" class="form-control rounded-3" id="cad-email-admin" name="email" placeholder="">
              <label class="fonte-modal" for="floatingInput">Login</label>
            </div>
            <div class="form-floating mb-3">
              <input type="password" class="form-control rounded-3" id="cad-senha-admin" name="senha" placeholder="">
              <label class="fonte-modal" for="floatingPassword">Senha</label>
              <div id="resp-modal" class="fonte-modal"></div>
            </div>
            <button id="botao-cad-modal-admin" class="w-100 mb-2 btn btn-lg rounded-3 btn-primary fonte-modal" type="button">Cadastrar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
<?php } ?>